Site/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/',include("post.urls",namespace="post")),
]

urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)

post/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^list/$',view=index,name='list'),
    url(r'^login/$',view=user_login,name='user_login'),
    url(r'^logout/$',view=user_logout,name='user_logout'),
    url(r'^user_profile_edit/$',view=user_profile_edit,name='user_profile_edit'),
    url(r'^user_register/$',view=user_register,name='user_register'),
    url(r'^update/(?P<id>[0-9]+)/$',view=changing,name='update'),
]

post/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):

    title=models.CharField(verbose_name="Ad",max_length=123,default="Başlık")
    image1=models.ImageField(verbose_name="Profil",blank=True,null=True)

    who=models.TextField(max_length=500,verbose_name="Hakkımda",blank=True,default="Kim")
    what_to_do=models.TextField(max_length=500,verbose_name="Ne Yaparım ?",blank=True,default="Ne yapar")

    interested_1=models.TextField(max_length=500,verbose_name="İlgi Alanlarım 1",blank=True,default="İlgi Alanı")
    img1=models.ImageField(verbose_name="İmg 1",blank=True)
    interested_2=models.TextField(max_length=500,verbose_name="İlgi Alanlarım 2",blank=True,default="İlgi Alanı")
    img2 = models.ImageField(verbose_name="İmg 2",blank=True)

    interested_3=models.TextField(max_length=500,verbose_name="İlgi Alanlarım 3",blank=True,default="İlgi Alanı")
    img3 = models.ImageField(verbose_name="İmg 3",blank=True)

    def __str__(self):
        return "{} - {} ".format(self.title,self.id)

post/forms.py
from django import forms
from .models import Post
from django.contrib.auth.models import User
class DetailForm(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        super(DetailForm, self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs={"class":"form-control"}
        self.fields["interested_1"].widget.attrs["rows"]=15
        self.fields["interested_2"].widget.attrs["rows"]=15
        self.fields["interested_3"].widget.attrs["rows"]=15
        self.fields["who"].widget.attrs["rows"]=15
        self.fields["what_to_do"].widget.attrs["rows"]=15

    class Meta:
        model=Post
        fields=['title','image1','who','what_to_do','interested_1','img1','interested_2','img2','interested_3','img3',]

class LoginForm(forms.Form):
    username = forms.CharField(max_length=150, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    password = forms.CharField(max_length=100, required=True,widget=forms.PasswordInput(attrs={"class": "form-control"}))

class UserRegisterForm(forms.ModelForm):

    username = forms.CharField(max_length=100, label='Kullanıcı Adı')
    password = forms.CharField(max_length=100, label='Parola', widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=100, label='Parola Doğrulama', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
            'password2'
        ]

    def clean_password2(self):
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password and password2 and password != password2:
            raise forms.ValidationError("Şifreler eşleşmiyor!")
        return password2
    
    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {"class": "form-control"}
        
class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model=User
        fields =["first_name","last_name","username","email"]

    def __init__(self, *args, **kwargs):
        super(UserProfileEditForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {"class": "form-control"}

post/views.py
from django.shortcuts import render,get_object_or_404,HttpResponseRedirect,reverse
from .models import Post
from .forms import DetailForm,LoginForm,UserRegisterForm,UserProfileEditForm
from django.contrib.auth import  authenticate,login,logout
from django.contrib.auth.decorators import login_required


def index(request):
    posts=Post.objects.last()
    return render(request,"post/index.html",context={"posts":posts})


@login_required(login_url='/index/login/')
def changing(request,id):#PostUpdate

    post=get_object_or_404(Post,id=id)
    form=DetailForm(request.POST or None,request.FILES or None,instance=post)

    if form.is_valid():
        form.save(commit=True)
        return HttpResponseRedirect(reverse("post:list"))
    return render(request,"post/update_form.html",context={'forms':form})

def user_login(request):
    if  request.user.is_authenticated():
        return HttpResponseRedirect(reverse("post:list"))


    form=LoginForm(request.POST or None)

    if form.is_valid():
        yetkili_mi=authenticate(username=form.cleaned_data["username"],password=form.cleaned_data["password"])
        if yetkili_mi:
            login(request,yetkili_mi)
            return HttpResponseRedirect(reverse("post:list"))

    return render(request,"post/login_form.html",context={"forms":form})


def user_profile_edit(request):#UserProfile
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse("post:list"))


    form=UserProfileEditForm(request.POST or None,instance=request.user)

    if form.is_valid():
        form.save(commit=True)
        return HttpResponseRedirect(reverse("post:list"))

    return render(request, "post/user_profile_edit.html", context={'forms': form})


def user_register(request):
    if  request.user.is_authenticated():
        return HttpResponseRedirect(reverse("post:list"))


    form=UserRegisterForm(request.POST or None)

    if form.is_valid():
        user=form.save(commit=False)
        user.set_password(form.cleaned_data["password"])
        user.save()

        yetki_var_mi=authenticate(username=form.cleaned_data["username"],password=form.cleaned_data["password"])

        if yetki_var_mi:
            login(request,user)
            return HttpResponseRedirect(reverse("post:list"))

    return render(request,"post/user_register.html",context={'forms':form})

def user_logout(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse("post:list"))


    logout(request)
    return HttpResponseRedirect(reverse("post:list"))

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{{ posts.title }}</title>
</head>
<body>
<script rel="script" src="{% static 'js/jquery.min.js' %}"></script>
<script rel="script" src="{% static 'js/bootstrap.min.js' %}"></script>

{% include 'tema.html' %}



</body>
</html>

templates/form.html
{% for form in forms %}
    <div class="for-group">
        {{ form.label_tag }}
        {{ form }}<br><br>
        {% if form.errors %}
            {{ form.errors }}
        {% endif %}
        <h4 style="color:#fff">{% if form.help_text %}</h4>
        <small style="color:#fff">{{ form.help_text|safe }}</small>
        {% endif %}
    </div>
{% endfor %}

templates/navbar.html
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'post:list' %}" style="color:#fff" ><b>{{ posts.title }}</b></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">

                {% if request.user.is_authenticated %}
                <li><a href="{% url 'post:update' posts.id %}">​<span class="glyphicon glyphicon-pencil"></span>Düzenle</a></li>
                <li class="drowdown">
                  <a  href="#" data-toggle="dropdown" style="color:#f0f0f0"><i class="fa fa-user"></i>
                        <span class="glyphicon glyphicon-eye-open"></span> {{ request.user.get_full_name }}<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'post:user_profile_edit' %}">​<span class="glyphicon glyphicon-cog"></span>Profil</a></li>
                     <li class="divider"></li>
                    <li><a href="{% url 'post:user_logout' %}">​<span class="glyphicon glyphicon-log-out"></span>Çıkış</a></li>
                    {% else %}
                    <li><a href="#kim"> Kim </a></li>
                    <li><a href="#ne">Ne Yapar</a></li>
                    <li><a href="#ilgialanlari">İlgi Alanları</a></li>
                      <li class="drowdown">
                      <a  href="#" data-toggle="dropdown"><i class="fa fa-user"></i>
                          <span class="glyphicon glyphicon-th-list"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="{% url 'post:user_login' %}">​<span class="glyphicon glyphicon-log-in"></span>Giriş</a></li>
                         <li class="divider"></li>
                        <li><a href="{% url 'post:user_register' %}">​<span class="glyphicon glyphicon-user"></span>Kayıt</a></li>
                     </ul>
                  </ul>
                {% endif %}

      </ul>
    </div>
  </div>
</nav>

templates/post/index.html
{% extends 'base.html' %}
{% load static %}
{% include 'navbar.html' %}

{% block body %}


{% endblock %}

templates/post/login_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/backgr.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>{{ posts.title }}</title>
</head>
<body>

{% include 'tools.html' %}
<div class="container">

    <div class="row">
          <div class="col-lg-5 col-lg-offset-3 col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2  ">
                    <h1 style="color:#fff"><b> Giriş Yap </h1><hr>
                    <form method="post" action="{% url 'post:user_login' %}">
                        {% csrf_token %}
                        {% include 'form.html' %}
          <div class="col-lg-5 col-lg-offset-3 col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2  ">
                             <input  type="submit" value="Giriş" class="btn btn-default btn-lg">
                            <a href="{% url 'post:user_register' %}"  class="btn btn-primary btn-md" > Kaydol </a>
                        </div>

                    </form>
            </div>
    </div>
</div>
</body>
</html>

templates/post/update_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/backgr.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>{{ posts.title }}</title>

</head>
<body>
{% include 'tools.html' %}
<div class="container">
    <div class="row">
      <div class="col-lg-5 col-lg-offset-3 col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2  ">
          <h1 class="page-header" style="color:#fff"> Post Update</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'form.html' %}
                <div class="col-lg-5 col-lg-offset-3 col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2  ">
                <input class="btn btn-default btn-lg" type="submit" value="Güncelle">
                </div>
            </form>
    </div>

    </div>
</div><hr>
</body>
</html>

templates/post/user_profile_edit.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/backgr.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>{{ posts.title }}</title>
</head>
<body>
{% include 'tools.html' %}

<div class="container">

    <div class="row">
          <div class="col-lg-5 col-lg-offset-3 col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2  ">
                    <h1 style="color:#fff"><b>Profil Güncelleme Formu</h1><hr>
                    <form method="post" action="{% url 'post:user_profile_edit' %}">
                        {% csrf_token %}
                        {% include 'form.html' %}
                        <input  type="submit" value="Güncelle" class="btn btn-success">

                    </form>
            </div>
    </div>
</div>
</body>
</html>

templates/post/user_register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/backgr.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>{{ posts.title }}</title>
</head>
<body>
{% include 'tools.html' %}

<div class="container">

    <div class="row">
          <div class="col-lg-5 col-lg-offset-3 col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2  ">
              <h1 style="color:#fff"><b>Kayıt Formu</b></h1><hr>
                    <form method="post" action="{% url 'post:user_register' %}">
                        {% csrf_token %}
                        {% include 'form.html' %}
                  <div class="col-lg-12 col-lg-offset-3 col-md-8 col-md-offset-2 col-xs-12 col-xs-offset-1  ">
                        <input type="submit"  value="Kaydet" class="btn btn-default btn-lg">
                      <a href="{% url 'post:user_login' %}" style="color:#fff;margin-left:20px " > <small>Bir hesabınız mı var ?</small> </a><br>
                  </div>
                    </form>
            </div>
    </div>
</div><hr>
</body>
</html>

templates/tema.html
{% include 'navbar.html' %}
<!-- First Container -->


<div id="kim" class="container-fluid bg-1 text-center">
  <h3 class="margin">Kimdir ?</h3>
    {% if posts.image1 %}
      <img src="{{ posts.image1.url }}" class="img-responsive img-circle margin" style="display:inline" alt="profil" width="350" height="350">
    {% endif %}
    <h3>
        <b>{{ posts.title }}</b><br><br>
        {{ posts.who }}
  </h3>
</div>

<!-- Second Container -->
<div id="ne" class="container-fluid bg-2 text-center">
  <h3 class="margin">Ne Mi Yapar ?</h3>
  <h3>{{ posts.what_to_do }}</h3><br>
  {% if not request.user.is_authenticated %}
    <a href="#" class="btn btn-default btn-lg">
    <span class="glyphicon glyphicon-search"></span> Search
  </a>
  {% endif %}

</div>

<!-- Third Container (Grid) -->
<div id="ilgialanlari" class="container-fluid bg-3 text-center">
  <h3 class="margin">İlgi Alanları</h3><br>

  <div class="row">
    <div class="col-sm-4">
      <p>{{ posts.interested_1 }}</p>
      <img src="{{ posts.img1.url }}" class="img-responsive margin" style="width:100%" alt="Image">
    </div>
    <div class="col-sm-4">
      <p>{{ posts.interested_2 }}</p>
      <img src="{{ posts.img2.url }}" class="img-responsive margin" style="width:100%" alt="Image">
    </div>
    <div class="col-sm-4">
      <p>{{ posts.interested_3 }}</p>
      <img src="{{ posts.img3.url }}" class="img-responsive margin" style="width:100%" alt="Image">
    </div>
  </div>
</div>

<!-- Footer -->
<footer class="container-fluid bg-4 text-center">
  <p>Every thing for learning Django </p>
  <small>This template designed by w3school</small>
</footer>

templates/tools.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand btn-lg" style="color:#fff" href="{% url 'post:list' %}"><span class="glyphicon glyphicon-home"></span></a>
    </div>
  </div>
</nav>